name: agent pool testing
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'   # every Monday at 00:00 UTC
  push:
    branches:
      - main

jobs:
  cleanup:
    runs-on: self-hosted   # self-hosted agent
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cleanup stale branches
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRY_RUN: true       # Set to false to actually delete branches
          DAYS: 30           # Branch age threshold
        run: |
            bash cleanup_repos.sh
        #   source "$GITHUB_WORKSPACE/cleanup_repos.sh"
